### ISSUE TITLE
App design discovery

### ISSUE THREAD

**Issue by Belfast82** [Belfast82/Streamskip#2]
**Is your feature request related to a problem? Please describe.**
We need to allow time to draw out the application design. We need to know what input and submission buttons for a full fledged application. This could be a raw first draft that will be modified.

**Describe the solution you'd like**
Something as simple as a paper napkin drawing will show the UI is sufficient.

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by esaith** [comment]
The basic views can be found at:
https://github.com/esaith/SkipStream/blob/main/Notes

The main page of the chrome extension will be a modal that is available on Netflix.com. Netflix will be the first test stream. In later versions, most streaming services should be available.

On page load, the modal will be hidden to the right of the screen with only a tab button available. On tab click, the modal will slide leftward to show the main page of the extension. The category and timespan entries that currently exist will be listed. The user can enable Blackout and Mute option for all timespans within a category. 

Each timespan entry will have a flag button. This will allow users to flag entries to be incorrect timespan, inappropriate category, or needs to be deleted. A different suggestion could be thumbs up/down but not sure how this may make sense.

An [Add/Edit] button will be available to add and edit timespan entries. On first version, additional of timespan entries only. 

A [Settings] button to allow setting default settings. Whatever the settings chosen, on page load the Blackout and Mute toggles per category should be set on the main page. Later versions may include profiles. Kids would have higher restrictions than young adult than non-filtered.

**Comment by Belfast82** [comment]
Passed by QA
